var paca_slotduration = '00:30:00';
var paca_scrolltime = '08:00:00';
var paca_mitime = '08:00:00';
var paca_maxtime = '18:00:00';
var paca_sloteventover = false;
var paca_alldayslot = true;
var paca_alldaytext = 'Todo el Dia';
var paca_editable = false;
var paca_selectable = false;
